import type { ActivityDirection, ActivityKind } from "@/types/activity";
import type { DayPeriod } from "@/types/day-period";
import type { Place } from "@/types/place";

export type PeriodRecommendationStatus = "idle" | "loading" | "ready" | "empty" | "error";

export const maxPeriodRecommendationRefreshes = 2;

export const periodRecommendationLimits = {
   maximumRequestBodyBytes: 32_768,
   maximumExcludedPlaceIds: 50,
   maximumCommittedStops: 3,
   maximumSessionSeedLength: 128,
   maximumIdentifierLength: 160,
   maximumPlaceNameLength: 200,
   maximumPlanningDaysAhead: 366,
} as const;

export type PeriodRecommendationErrorCode = "INVALID_JSON" | "REQUEST_TOO_LARGE" | "INVALID_REQUEST" | "INVALID_DATE" | "INVALID_GEOGRAPHY" | "PROVIDER_TIMEOUT" | "PROVIDER_ERROR" | "RATE_LIMITED";

export type CommittedStopContext = Readonly<{
   placeId: string;
   placeName: string;

   dayPeriod: DayPeriod;
   resolvedActivity: ActivityKind;

   latitude: number | null;
   longitude: number | null;
}>;

export type PeriodRecommendation = Readonly<{
   place: Place;

   reason: string;

   bestWindow: string;

   resolvedActivity: ActivityKind;
}>;

export type PeriodRecommendationRequest = Readonly<{
   metroRegionId: string;
   municipalityId: string;
   localAreaId: string;

   dayPeriod: DayPeriod;

   activityDirection: ActivityDirection;

   /**
    * Local calendar date in YYYY-MM-DD format.
    */
   planningDate: string;

   /**
    * Temporary anonymous seed generated by the browser for one planning
    * session.
    */
   sessionSeed: string;

   /**
    * Zero represents the original set. One and two represent the two
    * restrained alternate sets available for that part of the day.
    */
   variationIndex?: number;

   excludedPlaceIds: readonly string[];

   committedStops?: readonly CommittedStopContext[];
}>;

export type PeriodRecommendationResponse = Readonly<{
   dayPeriod: DayPeriod;

   recommendations: readonly PeriodRecommendation[];
}>;

export type PeriodRecommendationErrorResponse = Readonly<{
   error: string;
   code?: PeriodRecommendationErrorCode;
   requestId?: string;
   retryable?: boolean;
}>;
